### ISSUE TITLE
API Call: Create Order

### ISSUE THREAD

**Issue by thizume** [nyu-devops22-orders/orders#11]
**As a** an order management employee
 **I need** the ability to create order records
 **So that** I can record orders when customers make an order.
   
 ### Details and Assumptions
 * Each order record includes Order_ID, Customer_ID, Date, Status
   
 ### Acceptance Criteria  
   * Must return JSON

 ```gherkin
 When I received an order
 Then a new order record is created while any of the existing records are not modified
 ```

**Comment by smh9854** [comment]
I think for the initial order creation, the fields would be:
Date, Order_ID, Customer_ID, Order_Items_ID (to pull all items listed with this order record)

I'll submit a Create Orders Items ticket story to include the fields Order_ID, Product_ID, Product_SKU, Product_Price, Qty, Adj, Total

**Comment by thizume** [comment]
@smh9854 Thanks! Seems like I confused "orders" with "order items." Does Orders need to have Order_Items_ID? I think that two databases are linked as long as Order_Items has Order_ID. And if one order contains multiple items, one row in Orders would have multiple Order_IDs. (one-to-many relationship)

This page might help 
https://stackoverflow.com/questions/49186437/database-relation-between-orders-and-items/49191167
![image](https://user-images.githubusercontent.com/91509810/155849518-d8f10509-fd5b-459d-83da-040cb4519790.png)

**Comment by smh9854** [comment]
Yes you're right, only need one linked field. 

The order_id is a one-to-many relationship

**Comment by thizume** [comment]
Thanks! I updated the story :)
