### ISSUE TITLE
Create Cloud Foundry metadata files for deployment

### ISSUE THREAD

**Issue by scj10000** [nyu-devops22-orders/orders#57]
**As a** [developer]  
 **I need** [to create the necessary Cloud Foundry metadata files]  
 **So that** [so that IBM Cloud will know how to deploy your application]  
   
 ### Details and Assumptions
 * manifest.yml, Procfile, runtime.txt
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by smh9854** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/f664b6ee-37fd-4438-a0fe-b3a1dd5372f7?env_id=ibm:yp:us-south "nyu-order-service-sp2201"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/feab792f-5e52-4959-a71b-0dbb1abb0d70 "nyu-order-service-sp2201") deployed [orders](https://github.com/nyu-devops22-orders/orders/releases/tag/deploy-ibm-yp-us-south-smh9854-nyu.edu-dev-20220407-012306 "deploy-ibm-yp-us-south-smh9854-nyu.edu-dev-20220407-012306") to [dev](https://cloud.ibm.com/apps/ae4d128b-9ca1-40a7-abf2-09bb56debbc3?env_id=ibm:yp:us-south "ibm:yp:us-south:smh9854@nyu.edu:dev"), including commits 8d07c576447df76d7f8b1e07a904802dfe7e1d23, 657df6f85e54bb4c197a37f57ef6e941b09daff7
